<a href="https://colab.research.google.com/github/himiku/mafiai/blob/master/try_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
arr2D = np.array([[1,2,3],[2,3,4]])
arr1D = np.array([3,4,5])

# matix computational example
# arr2D = np.matrix([[1,2,3],[2,3,4]])
# arr1D = np.matrix([[3],[4],[5]])

[[a   b],[c   d]]  x   [[x],[y]] = [[ax+by],[cx+dy]]   

   


> [[1,2,3],[4,5,6]] x [[1].[2],[3]] = [[1.1+2.2+3.3],[4.1+5.2+6.3]] = [[14],[32]]



In [5]:
#try multitple
#arr2D.dot(arr1D)  
arr2D * arr1D

array([[ 3,  8, 15],
       [ 6, 12, 20]])

In [27]:
#dtype
arr2D.dtype
arr2D.astype('float64')

array([[1., 2., 3.],
       [2., 3., 4.]])

In [13]:
#try reshape
print(arr2D.shape)
print(arr1D.shape)
arr2D.reshape(3,2)

(2, 3)
(3,)


array([[1, 2],
       [3, 2],
       [3, 4]])

In [31]:
#numpy matrix array generator
np.zeros((3,3))
np.ones((3,3))
np.arange(1,10,2)
np.linspace(1,10,6)
np.random.random((3,3))
np.random.randint(1,10,(2,3))

array([[8, 3, 4],
       [4, 3, 3]])

In [39]:
#etc method
arr2D.min()
arr2D.max()
arr2D.mean() #rata-rata
arr2D.std()
arr2D.var()

0.9166666666666666